### PR TITLE
Implement COUNT, BYSETPOS, BYWEEKNO, EXDATE, EXRULE, and format()

### PR DESCRIPTION
**Pull request by snoopyjc**
Implement COUNT, BYSETPOS, BYWEEKNO, EXDATE, EXRULE, and new deparse (now format) method. Fix Issue #12. Update tests for 100% code coverage.

### CODE REVIEW

**Comment by kvh** [comment]
Amazing work, great to see expanded tests at 100% coverage, plus the "deparse" bonus functionality. Very cool. I prefer "format" over "deparse", in accordance with the strftime  strptime convention. Otherwise LGTM

**Comment by snoopyjc** [comment]
Ok I’ll push that name change. 

-joe

**Comment by snoopyjc** [comment]
Ok - it's all set!

**Comment by kvh** [comment]
You added some .swp files in that last commit. Remove and add to .gitignore?

**Comment by snoopyjc** [comment]
Sorry - stuff left by my editor - fixed!!

**Comment by kvh** [comment]
Live: https://pypi.org/project/recurrent/0.4.0/

**Comment by snoopyjc** [comment]
Thanks!  The 2 open issues can now be closed.

**Pull request merged**
