### PR TITLE
Fix issues 3, 13, 14, 15, 16, 17, 18

### PR DESCRIPTION
**Pull request by snoopyjc**
I fixed issues 3, 13 (except for the timezone), 14, 15, 16, 17, 18.  Please merge to master.

### CODE REVIEW

**Comment by kvh** [comment]
Thanks for the fixes

**Comment by snoopyjc** [comment]
You’re welcome. 

I closed the issues I opened. I commented on the others that can be closed. 

I didn’t do the timezone one because I don’t agree that it belongs there. I handle the TZ outside of the package when I use it. 

I wrote code that does the opposite of this - it takes a datetime or rrule and converts it back to english. Let me know if you think this belongs in the same package and I will submit it in a couple weeks (I’m having a big surgery tomorrow). 

Please update PyPI with 0.3.0. 

-joe

**Comment by kvh** [comment]
Agree on timezones. I would welcome the inverse functionality, sounds very cool. I'll look out for the PR

PyPI has been updated

**Comment by snoopyjc** [comment]
Ken:

Any recommendations on what I should call it?  deparse?  unparse? format?
--joe
P.S. Your email server doesn't work that well!

**Pull request merged**
